<?php

namespace AppBundle\Repository;

/**
 * CatQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
