<?php

namespace AppBundle\Repository;

/**
 * CatReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatReponseRepository extends \Doctrine\ORM\EntityRepository
{
}
