<?php

namespace AppBundle\Repository;

/**
 * FriendlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendlistRepository extends \Doctrine\ORM\EntityRepository
{
}
