<?php

namespace AppBundle\Repository;

/**
 * OtherUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherUserRepository extends \Doctrine\ORM\EntityRepository
{
}
