<?php

namespace AppBundle\Repository;

use AppBundle\Model\JsonConverter;

use Doctrine\Common\Util\Debug;
/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRandom($category){
        $json = new JsonConverter();
        $questions = $this->createQueryBuilder('q')
                        ->where('q.catQuestion = :cat')
                        ->setParameter('cat', $category)
                        ->addSelect('RAND() as HIDDEN rand')
                        ->addOrderBy('rand')
                        ->setMaxResults(5)
                        ->getQuery()->getResult();

        array_map(function($item) use($json){
            $em = $this->getEntityManager()
                        ->createQuery('SELECT r FROM AppBundle:Reponse r WHERE r.catReponse = :cat')
                        ->setParameter('cat', $item->getCatReponse() )
                        ->getResult();

            $falsies = array();
            $n = 0;
            for($i = 0; $i < 3; $i++){
                $index = random_int(0, count($em)-1);

                while($em[$index]->getReponse() == $item->getReponse()){
                    $index = random_int(0, count($em)-1);
                }

                array_push($falsies, $em[$index]->getReponse());
                unset($em[$index]);
                $tmp = array_values($em);
                $em=$tmp;
            }
            //todo renvoyer 5 questions
            $json->addQuestion($item, $falsies);
        },$questions);

        return $json->toJson();
    }
}
