<?php

namespace AppBundle\Repository;

/**
 * UserInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
