AppBundle\Entity\UserInformation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserInformationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idUser:
            oneToOne:
                user:
                    targetEntity: User
                    joinColumn:
                        name: idUser
                        referenceColumn: id
            type: integer
            unique: true
        scoreTotal:
            type: integer
        username:
            type: string
            length: '40'
            unique: true
        imgUrl:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
