AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            oneToOne: 
                userInformation:
                    targetEntity: User
                    mappedBy: userInforamtion
                    onDelete: CASCADE
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        password:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            unique: true
        idExt:
            type: string
            length: 255
            nullable: true
        accountType:
            type: string
            length: 255
            nullable: false
        token: 
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
